### ISSUE TITLE
Better organization

### ISSUE THREAD

**Issue by jochasinga** [pranavgarg/algorithms#7]
@pranavgarg maybe it's best to start reorganizing directories into something like:

```
data_structures
├── python
├── cpp
└── javascript
          └── linkedlist.js
```

**Comment by pranavgarg** [comment]
Makes sense lets do it.

Pranav garg

**Comment by pranavgarg** [comment]
hey pan, have sent you the invite for being collaborator and review the http://github.com/pranavgarg/algorithms/pull/9
